apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-static-config
  namespace: kubeingress-system
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    static_resources:
      listeners:
      - name: ingress_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                - name: gallery_tenant
                  domains: ["gallery.local", "gallery.local:*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: gallery_cluster

                - name: enigma_tenant
                  domains: ["enigma.local", "enigma.local:*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: enigma_cluster

      clusters:
      - name: gallery_cluster
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: gallery_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gallery-service.gallery.svc.cluster.local
                    port_value: 80

      - name: enigma_cluster
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: enigma_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: enigma-service.enigma.svc.cluster.local
                    port_value: 80
