CREATE TABLE IF NOT EXISTS routes (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    host VARCHAR(255) NOT NULL UNIQUE,
    upstream_service VARCHAR(255) NOT NULL,
    upstream_port INT NOT NULL DEFAULT 80,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
